Add Memo field
hashgraph/hedera-protobufs-java pull request #50
Opened 2021-02-03 20:11 UTC by anighanta

Added memo field to Account,File,Schedule and Token create/update/getInfo transactions

Signed-off-by: Anirudh Ghanta <anirudh.ghanta@hedera.com>

2021-02-03 20:16 UTC, tinker-michaelj requested changes
LGTM! Only we don't want to change the _pom.xml_ version in `master`.

2021-02-03 20:16 UTC, tinker-michaelj commented on pom.xml
> +  <version>0.12.0-issue.960-963-SNAPSHOT</version>
We won't change this `version` element in `master` until it's time for a new release.

We use an issue-specific `version` in the branch's _pom.xml_ just to deploy it to the snapshot repository (so branches in `hashgraph/hedera-services` can use it). But before merging to `master`, we revert that.

2021-02-04 21:28 UTC, steven-sheehy requested changes

2021-02-04 21:28 UTC, steven-sheehy commented on src/main/proto/CryptoUpdate.proto
> +    string memo = 14; // The new account memo, assumed to be Unicode encoded with UTF-8 (at most 100 bytes)
While creates should be a `string`, update transactions need to be a `com.google.protobuf.StringValue` per Leemon:
> so that we can tell the difference between leaving it out (and so not changing it) vs. putting it in with an empty string (and so changing it to the empty string)`

2021-02-04 21:28 UTC, steven-sheehy commented on src/main/proto/TokenUpdate.proto
> +    string memo = 13; // The new token memo, assumed to be Unicode encoded with UTF-8 (at most 100 bytes)
StringValue

2021-02-04 21:28 UTC, steven-sheehy commented on src/main/proto/FileUpdate.proto
> +    string memo = 5; // The new file memo, assumed to be Unicode encoded with UTF-8 (at most 100 bytes)
StringValue

2021-02-04 21:28 UTC, steven-sheehy commented on src/main/proto/CryptoCreate.proto
> +    string memo = 13; // the memo that was submitted as part of the Account creation (max 100 bytes)
Every memo description seems to vary. Can we make them all consistent? Also, we don't need to mention UTF-8 since protobuf protocol guarantees strings are always UTF-8 encoded. Perhaps use something like the below for all?

`The memo associated with the ${entity} (max 100 bytes)`

2021-02-04 22:57 UTC, tinker-michaelj commented
Closed pending approval of https://github.com/hashgraph/hedera-protobufs/pull/3

2021-02-04 22:57 UTC, closed without merging