TokenCreate: Types and max supply
hashgraph/hedera-protobufs-java pull request #67
Opened 2021-05-18 14:38 UTC by failfmi

**Related issue(s)**:
Closes #None

**Summary of the change**:
* Introduce `TokenType` enum
* Introduce `TokenRepresentationType` enum
* `TokenCreateTransactionBody`: add types and max supply

**External impacts**:
None.

2021-05-18 14:42 UTC, tinker-michaelj approved these changes
LGTM

2021-05-18 14:55 UTC, bugbytesinc commented on src/main/proto/TokenCreate.proto
> +    uint32 decimals = 3; // For tokens of type FUNGIBLE - the number of decimal places a token is divisible by. For tokens of type NON_FUNGIBLE - value must be 0.
In my opinion, changing the definition at this time is problematic.  Why can't we use a new protobuf message to represent a NFT instead?

2021-05-18 14:57 UTC, bugbytesinc commented
I don't think we should be changing the meaning of existing protobuf that's been published.  Why can't there be a new message representing the NFT instead?  Wont overloading the meaning of existing protobuf will lead to more logic branches in the code that consumes it?  Making it harder to maintain?

2021-05-18 15:12 UTC, steven-sheehy commented on src/main/proto/TokenCreate.proto
> +    uint32 decimals = 3; // For tokens of type FUNGIBLE - the number of decimal places a token is divisible by. For tokens of type NON_FUNGIBLE - value must be 0.
We originally went down the path of a separate NFT service. The [rationale](https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-17.md#rationale) for this approach is documented in the HIP.

2021-05-18 15:28 UTC, steven-sheehy requested changes
Why are we first checking into hedera-protobufs-java? hedera-protobufs is considered the authoritative source with changes flowing down from there. Might be fine, but please remember to open another PR in hedera-protobufs once this is merged.

2021-05-18 15:28 UTC, steven-sheehy commented on src/main/proto/TokenCreate.proto
> +    int64 maxSupply = 19; // IWA Compatibility. For tokens of type FUNGIBLE - the maximum number of tokens that can be in circulation. For tokens of type NON_FUNGIBLE - the maximum number of NFTs (se
These should all mention what the default is if not explicitly set. Or if they're required state so. I'm guessing if `maxSupply` is left empty it defaults to zero but internally zero is interpreted as max long?

2021-05-18 16:50 UTC, failfmi commented on src/main/proto/TokenCreate.proto
> +    int64 maxSupply = 19; // IWA Compatibility. For tokens of type FUNGIBLE - the maximum number of tokens that can be in circulation. For tokens of type NON_FUNGIBLE - the maximum number of NFTs (se
Yes, if left empty will default to zero. So far (not merged), the state interprets **zero** `maxSupply` as infinite, because there is no point in creating a token with a max supply of **zero**.

2021-05-18 16:55 UTC, failfmi commented
> Why are we first checking into hedera-protobufs-java? hedera-protobufs is considered the authoritative source with changes flowing down from there. Might be fine, but please remember to open another PR in hedera-protobufs once this is merged.

We have decided to check into `hedera-protobufs-java` first, so that everyone participating in the development could easily compile the protobufs locally and use them in `hedera-services`. Plus, `nft` changes will be made against the [nfts](https://github.com/hashgraph/hedera-protobufs-java/tree/nfts) branch.

2021-05-18 17:01 UTC, ijungmann requested changes
A couple questions regarding `TokenRepresentationType`, as this seems to have some impact on the mirror node design.

2021-05-18 17:01 UTC, ijungmann commented on src/main/proto/TokenCreate.proto
> +    uint64 initialSupply = 4; // Specifies the initial supply of tokens to be put in circulation. The initial supply is sent to the Treasury Account. The supply is in the lowest denomination possible
Is the impetus for having NON_FUNGIBLE Type always be 0 here so that serial numbers do not need to be created at token create time?  As mentioned above, my understanding is serial numbers could now be created for FUNGIBLE tokens as well.

2021-05-18 17:13 UTC, steven-sheehy commented on src/main/proto/TokenCreate.proto
> +    int64 maxSupply = 19; // IWA Compatibility. For tokens of type FUNGIBLE - the maximum number of tokens that can be in circulation. For tokens of type NON_FUNGIBLE - the maximum number of NFTs (se
I would still like the comments updated for all three of these fields noted above to reflect default or required values.

2021-05-19 06:06 UTC, rbair23 commented on src/main/proto/TokenCreate.proto
> +    int64 maxSupply = 19; // IWA Compatibility. For tokens of type FUNGIBLE - the maximum number of tokens that can be in circulation. For tokens of type NON_FUNGIBLE - the maximum number of NFTs (se
Do we anywhere else assume that 0 means max? I think this will be surprising to people.

2021-05-19 06:09 UTC, rbair23 commented on src/main/proto/BasicTypes.proto
> +    Unique = 1; // Individually traced and can carry unique properties (e.g. serial number).
Of the four combinations there are only three valid combinations: Fungible-Common, Fungible-Unique, NonFungible-Unique. Somewhere this needs to be documented. In answer to your question, yes, Fungible-Unique would end up with serial numbers and such just like NonFungible (which is always unique).

2021-05-19 06:12 UTC, rbair23 commented on src/main/proto/TokenCreate.proto
> +    uint64 initialSupply = 4; // Specifies the initial supply of tokens to be put in circulation. The initial supply is sent to the Treasury Account. The supply is in the lowest denomination possible
Yes, my understanding is that we require 0 for NFT (and Fungible-Unique as you mention!) because each unique token must be minted individually so that it can acquire whatever meaning (reference to external data for example) that is needed, since once minted, it is too late to update. We could have some kind of batch process.

2021-05-19 14:01 UTC, steven-sheehy approved these changes

2021-05-19 14:38 UTC, Daniel-K-Ivanov commented on src/main/proto/BasicTypes.proto
> +    Unique = 1; // Individually traced and can carry unique properties (e.g. serial number).
We will update [HIP-17](https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-17.md) reflecting the new changes.

2021-05-19 14:40 UTC, Daniel-K-Ivanov commented on src/main/proto/TokenCreate.proto
> +    uint64 initialSupply = 4; // Specifies the initial supply of tokens to be put in circulation. The initial supply is sent to the Treasury Account. The supply is in the lowest denomination possible
@ljianghedera yes, that is the exact reason. I will make sure to document it in HIP-17

2021-05-19 15:40 UTC, ijungmann commented on src/main/proto/BasicTypes.proto
> +    Unique = 1; // Individually traced and can carry unique properties (e.g. serial number).
Alright, that clears it up a bit.  I'll be interested to see how this affects further transactions (I'm sure transferring will have some changes from this).

2021-05-19 15:40 UTC, ijungmann commented on src/main/proto/TokenCreate.proto
> +    uint64 initialSupply = 4; // Specifies the initial supply of tokens to be put in circulation. The initial supply is sent to the Treasury Account. The supply is in the lowest denomination possible
Got it.

2021-05-20 08:47 UTC, failfmi commented on src/main/proto/TokenCreate.proto
> +    int64 maxSupply = 19; // IWA Compatibility. For tokens of type FUNGIBLE - the maximum number of tokens that can be in circulation. For tokens of type NON_FUNGIBLE - the maximum number of NFTs (se
I have not found anywhere else this assumption. On the other hand, every time a Token is created, a max supply would need to be provided, requiring the creator to provide a max supply > 0. Then, if you would like it to be `INFINITE`, you would need to set `Long.MAX_VALUE` in the given language (using the sdks - C, Go, Java, JavaScript).

I think that scenarios like: `I have created a token with max supply of 50 000 (maybe it will be enough), got 50 000, now I cannot mint anymore, what I am going to do` might appear (shoot oneself in the foot). Of course, this depends on the user experience of how token creation will be done.

2021-05-20 11:38 UTC, bugbytesinc commented
Point of Order:  Should this conversation not be here: https://github.com/hashgraph/hedera-improvement-proposal/discussions/74 instead?

2021-05-20 17:39 UTC, ijungmann approved these changes

2021-05-31 12:05 UTC, failfmi commented
Closing this, feel free to join the conversation for all the changes regarding the NFT feature [here](https://github.com/hashgraph/hedera-protobufs-java/pull/68) (includes the changes from this PR).

2021-05-31 12:05 UTC, closed without merging