Feature: NFT Tokens
hashgraph/hedera-protobufs-java pull request #68
Opened 2021-05-25 12:27 UTC by failfmi

**Related issue(s)**:
Closes #None

**Summary of the change**:
* Based on [HIP-17](https://github.com/LimeChain/hedera-improvement-proposal/blob/hip/hts-temp/HIP/hip-17.md)

**External impacts**:
None.

2021-05-25 14:34 UTC, Daniel-K-Ivanov submitted a review, later dismissed

2021-05-25 18:33 UTC, rbair23 commented on src/main/proto/CryptoGetInfo.proto
> +        int64 ownedNFTs = 17; // The number of NFTs owned by this account
In some places our API uses "NFT" and in some it uses "Nft". What do we want to use?

2021-05-26 06:51 UTC, Nana-EC reviewed
Looking good, some non blocking clarifications from my end as they may or may not affect design.

2021-05-26 06:51 UTC, Nana-EC commented on src/main/proto/TokenMint.proto
> +    bytes metadata = 3; // Applicable to tokens of type NON_FUNGIBLE_UNIQUE. The metadata for the given NFT instance that is being created. Maximum allowed size is 100 bytes
Is the implication that `TokenMint` can only mint one NFT at time?
Would you have to submit X `TokenMint` transactions to mint X new NFT's?
I might have expected a `repeated bytes` here to specify a list of NFT metadata contents

2021-05-26 06:51 UTC, Nana-EC commented on src/main/proto/TransactionReceipt.proto
> +    int64 serialNumber = 14;
Similar to above. Are we limited to an NFT per transaction?
I would have expected a `repeated int64` for all the new NFT's minted.

2021-05-26 06:51 UTC, Nana-EC commented on src/main/proto/TokenMint.proto
> +    bytes metadata = 3; // Applicable to tokens of type NON_FUNGIBLE_UNIQUE. The metadata for the given NFT instance that is being created. Maximum allowed size is 100 bytes
Circling back to the HIP I see this is per design.
However, given the nature of NFTs we should consider this explicit limitation sooner rather than later.
Currently I can mint any number of `FUNGIBLE_COMMON` in a single transaction. I might want to do a similar action with `NON_FUNGIBLE_UNIQUE` providing `metadata` for each as they may differ slightly e.g. Mint 5 NFT's with metadata  - option1, option2, option3, option4, option5.

2021-05-26 06:51 UTC, Nana-EC commented on src/main/proto/TransactionReceipt.proto
> +    int64 serialNumber = 14;
Circling back to the HIP I see this is per design.
However, given the nature of NFTs we should consider this explicit limitation sooner rather than later.

2021-05-26 06:51 UTC, Nana-EC commented on src/main/proto/TransactionReceipt.proto
> +    // In the receipt of a TokenMint for tokens of type NON_FUNGIBLE_UNIQUE, the serial number of the newly created NFT
Would `newTotalSupply` on line 105 now represent the total number of NFTs for the given `tokenID`?
If so comment should be updated to highlight this.

2021-05-26 12:47 UTC, Daniel-K-Ivanov commented on src/main/proto/TransactionReceipt.proto
> +    // In the receipt of a TokenMint for tokens of type NON_FUNGIBLE_UNIQUE, the serial number of the newly created NFT
Yes, `newTotalSupply` would represent total number of NFTs issued for the given `tokenID`

2021-05-26 17:22 UTC, steven-sheehy requested changes

2021-05-26 17:22 UTC, steven-sheehy commented on src/main/proto/GetAccountNftInfo.proto
> +    AccountID accountId = 2; // The Account for which information is requested
```suggestion
    AccountID accountID = 2; // The Account for which information is requested
```

2021-05-26 17:22 UTC, steven-sheehy commented on src/main/proto/GetAccountNftInfo.proto
> +    AccountID accountId = 2; // The Account that this record is for
```suggestion
    AccountID accountID = 2; // The Account that this record is for
```

2021-05-26 17:22 UTC, steven-sheehy commented on src/main/proto/GetNftInfo.proto
> +    TokenID tokenId = 1; // The (non-fungible) token of which this NFT is an instance
```suggestion
    TokenID tokenID = 1; // The (non-fungible) token of which this NFT is an instance
```

2021-05-26 17:22 UTC, steven-sheehy commented on src/main/proto/GetNftInfo.proto
> +message NftId {
```suggestion
message NftID {
```

2021-05-26 17:22 UTC, steven-sheehy commented on src/main/proto/GetNftInfo.proto
> +    NftId nftId = 2; // The ID of the NFT
```suggestion
    NftID nftID = 2; // The ID of the NFT
```

2021-05-26 17:22 UTC, steven-sheehy commented on src/main/proto/GetNftInfo.proto
> +    NftId nftId = 1; // The ID of the NFT
```suggestion
    NftID nftID = 1; // The ID of the NFT
```

2021-05-26 17:22 UTC, steven-sheehy commented on src/main/proto/GetNftInfo.proto
> +    AccountID owner = 2; // The current owner of the NFT
Should have `ID` appended. I think a field named `accountID` would be better than owner since it matches the name of the field in `GetAccountNftInfoResponse` and it is assumed that any account ID listed for a NFT would be its owner.
```suggestion
    AccountID accountID = 2; // The current owner of the NFT
```

2021-05-26 17:22 UTC, steven-sheehy commented on src/main/proto/GetAccountNftInfo.proto
> +    repeated NftInfo nfts = 3; // List of NFTs associated to the account
Each `NftInfo` also contains the same `accountID` so it is redundant to specify it in both places.

2021-05-26 17:22 UTC, steven-sheehy commented on src/main/proto/GetTokenNftInfo.proto
> +    TokenID tokenId = 2; // The ID of the token for which information is requested
```suggestion
    TokenID tokenID = 2; // The ID of the token for which information is requested
```

2021-05-26 17:22 UTC, steven-sheehy commented on src/main/proto/GetTokenNftInfo.proto
> +    TokenID tokenId = 2; // The Token with type NON_FUNGIBLE that this record is for
```suggestion
    TokenID tokenID = 2; // The Token with type NON_FUNGIBLE that this record is for
```

2021-05-26 20:13 UTC, ijungmann commented on src/main/proto/GetNftInfo.proto
> +message GetNftInfoQuery {
If/when support for `fungible unique` tokens is added, would it be expected that more queries would be added for that?  I'm wondering if this naming convention is too limiting, we're having the same discussion on the mirror node side.

2021-05-28 15:19 UTC, steven-sheehy requested changes

2021-05-28 15:33 UTC, steven-sheehy commented on src/main/proto/GetTokenNftInfo.proto
> +message GetTokenNftInfoQuery {
Leemon preferred `TokenGetNftInfosQuery`

2021-05-31 12:06 UTC, Daniel-K-Ivanov commented on src/main/proto/TokenMint.proto
> +    bytes metadata = 3; // Applicable to tokens of type NON_FUNGIBLE_UNIQUE. The metadata for the given NFT instance that is being created. Maximum allowed size is 100 bytes
After the last meeting that we had discussing the HIP, we decided that it will be `repeated bytes metadata` instead of a single NFT. There will be a limit on the number of `metadata`s enforced by a global dynamic property

2021-05-31 12:08 UTC, Daniel-K-Ivanov commented on src/main/proto/TransactionReceipt.proto
> +    int64 serialNumber = 14;
After the last meeting that we had discussing the HIP, we decided that it will be `repeated bytes metadata` instead of a single NFT. Thus this property will be updated to `repeated int64 serialNumber`

2021-05-31 12:09 UTC, Daniel-K-Ivanov commented on src/main/proto/GetNftInfo.proto
> +message GetNftInfoQuery {
We've discussed this topic on the last weekly sync. Ultimately we decided that there will be new queries if/when `fungible unique` is supported

2021-05-31 14:52 UTC, steven-sheehy requested changes

2021-05-31 14:52 UTC, steven-sheehy commented on src/main/proto/Query.proto
> +        TokenGetNftInfoQuery tokenGetNftInfos = 56; // Get a list of NFTs for the token
Duplicate query

2021-05-31 15:24 UTC, steven-sheehy approved these changes
LGTM

2021-06-01 16:07 UTC, ijungmann submitted a review, later dismissed

2021-06-01 19:26 UTC, ijungmann commented on src/main/proto/BasicTypes.proto
> +    uint64 balance = 2; // Number of transferable units of the identified token. For token of type FUNGIBLE_COMMON - balance in the smallest denomination. For token of type NON_FUNGIBLE_UNIQUE - the
Will this also be the case for `TokenUnitBalance` for the balance file?

2021-06-01 19:29 UTC, steven-sheehy commented on src/main/proto/BasicTypes.proto
> +    uint64 balance = 2; // Number of transferable units of the identified token. For token of type FUNGIBLE_COMMON - balance in the smallest denomination. For token of type NON_FUNGIBLE_UNIQUE - the
It probably should to be consistent. If so, please update the comment for `TokenUnitBalance` in the streams folder.

2021-06-02 13:41 UTC, steven-sheehy submitted a review, later dismissed

2021-06-03 15:28 UTC, ijungmann commented on src/main/proto/TokenMint.proto
> +    repeated bytes metadata = 3; // Applicable to tokens of type NON_FUNGIBLE_UNIQUE. A list of metadata that are being created. Maximum allowed size of each metadata is 100 bytes
Can the metadata for an NFT ever be null/empty?

2021-06-04 11:55 UTC, Daniel-K-Ivanov commented on src/main/proto/TokenMint.proto
> +    repeated bytes metadata = 3; // Applicable to tokens of type NON_FUNGIBLE_UNIQUE. A list of metadata that are being created. Maximum allowed size of each metadata is 100 bytes
It seems that having empty `metadata` is pointless. It will be brought up for discussion.

2021-06-04 11:55 UTC, Daniel-K-Ivanov commented
LGTM!

2021-06-04 14:40 UTC, steven-sheehy reviewed
Is the 100K lines added normal? I'm guessing it's all auto-generated docs but seems really high want to confirm.

2021-06-04 14:40 UTC, steven-sheehy commented on src/main/proto/BasicTypes.proto
> +    repeated FeeData feeDataList = 3;
This will generate the awkward code `getFeeDataListList()`. What about `fees`?

2021-06-04 14:46 UTC, Daniel-K-Ivanov commented on src/main/proto/BasicTypes.proto
> +    repeated FeeData feeDataList = 3;
We were wondering about a proper name. Thanks for the suggestion. We will update it

2021-06-06 13:52 UTC, steven-sheehy submitted a review, later dismissed

2021-06-07 16:54 UTC, ijungmann approved these changes

2021-06-10 12:59 UTC, Daniel-K-Ivanov submitted a review, later dismissed

2021-06-11 04:58 UTC, ijungmann commented on src/main/proto/TokenMint.proto
> +    repeated bytes metadata = 3; // Applicable to tokens of type NON_FUNGIBLE_UNIQUE. A list of metadata that are being created. Maximum allowed size of each metadata is 100 bytes
Is it safe to assume that the serial numbers list in the `TransactionReceipt` will be in the order of the metadata list here so that one could easily identify which serial number goes to which metadata?  It would be problematic for the record file if order wasn't ensured.

2021-06-11 16:45 UTC, ijungmann commented on src/main/proto/BasicTypes.proto
> +}
How will this appear for minting, burning, etc?  Would it be that for minting, there would just be no sender, and for burning, wiping, etc. there would be no receiver?

2021-06-15 06:28 UTC, Daniel-K-Ivanov commented on src/main/proto/BasicTypes.proto
> +}
Yes, for minting there will be no sender and for burning wiping there will be no receiver. We will update the inline comments to reflect that

2021-06-25 21:11 UTC, closed without merging