Add a bool field to allow fractional fee to be charged to sender or receiver.
hashgraph/hedera-protobufs-java pull request #82
Opened 2021-08-04 22:12 UTC by ljianghedera

**Description**:

This PR adds one bool field to allow the user to decide the fractional custom fee to be charged to sender or receiver.

**Related issue(s)**:

Fixes #81

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-08-04 22:13 UTC, anighanta submitted a review, later dismissed

2021-08-04 22:24 UTC, qnswirlds submitted a review, later dismissed

2021-08-04 22:48 UTC, xin-hedera requested changes

2021-08-04 22:48 UTC, xin-hedera commented on src/main/proto/CustomFees.proto
> +  bool netOfTransfers = 4; // If true, assesses the fee to the sender, so the receiver gets the full amount from the token transfer list, and the sender is charged an additional fee; if false, the re
snake_case, for consistency

2021-08-06 16:31 UTC, xin-hedera approved these changes
LGTM

2022-11-16 07:54 UTC, closed without merging